### ISSUE TITLE
Build artifact and upload to github release page

### ISSUE THREAD

**Issue by zsluedem** [silius-rs/silius#167]
We should provide a way which users doesn't need to compile the bundler themselves. User could just download the binary and run the bundler.

**Comment by da-bao-jian** [comment]
Personally, as a user, I think a Docker file should suffice, so long as clear instruction is given. 

A binary is icing on the sugar, but it could introduce some issues:
-I don't know what the size of the aa-bundler binary would be, but as the project grows, the binary might reach the size limit for Github(2GB I believe)
-Binary files are not diffable. When you make changes to a binary file and upload it to GitHub, GitHub can't show you a diff like it can for text files. This makes version control slightly more difficult if the release tag was not applied properly


Just my two cents
