### ISSUE TITLE
The contract addresses of factory and paymaster can be provided (if any)

### ISSUE THREAD

**Issue by octavei** [silius-rs/silius#176]
The contract addresses of factory and paymaster can be provided (if any). This is very beneficial for our next test, thank you

**Comment by Vid201** [comment]
Hey @octavei , I am not sure what you mean by that. There are multiple factory smart contracts and paymasters. Do you mean including some of them in README.md or bundler whitelisting certain factories and paymasters?

**Comment by octavei** [comment]
including some of them in README.md

**Comment by octavei** [comment]
> Hey @octavei , I am not sure what you mean by that. There are multiple factory smart contracts and paymasters. Do you mean including some of them in README.md or bundler whitelisting certain factories and paymasters?

including some of them in README.md

**Comment by zsluedem** [comment]
Maybe we could just put something ONLY from https://github.com/eth-infinitism/account-abstraction (or something reliable). It is sometimes risky to put an address without auditing(understanding).

**Comment by zsluedem** [comment]
https://www.jiffyscan.xyz/paymasters?pageNo=1&pageSize=10 Jiffyscan got some good data about paymaster and factory.

**Comment by da-bao-jian** [comment]
> > Hey @octavei , I am not sure what you mean by that. There are multiple factory smart contracts and paymasters. Do you mean including some of them in README.md or bundler whitelisting certain factories and paymasters?
> 
> including some of them in README.md

[This](https://docs.google.com/spreadsheets/d/1QJEYDOr-AMD2bNAoupfjQJYJabFgdb2TRSyekdIfquM/edit#gid=1722929264)is the most comprehensive list I've came across. Bundler, Paymasters, and account factories. 

@Vid201 @zsluedem Should I add this to the README?

**Comment by Vid201** [comment]
> > > Hey @octavei , I am not sure what you mean by that. There are multiple factory smart contracts and paymasters. Do you mean including some of them in README.md or bundler whitelisting certain factories and paymasters?
> > 
> > including some of them in README.md
> 
> [This](https://docs.google.com/spreadsheets/d/1QJEYDOr-AMD2bNAoupfjQJYJabFgdb2TRSyekdIfquM/edit#gid=1722929264) is the most comprehensive list I've came across. Bundler, Paymasters, and account factories. 
> 
> @Vid201 @zsluedem Should I add this to the README? Then marked the ones that have been audited

Hmm, I am not sure about adding specific ones to the README.md (or code). I think it's fine at the moment to just add the link above to the README.md and show how to do whitelisting.
