### ISSUE TITLE
Support loading private key

### ISSUE THREAD

**Issue by Vid201** [silius-rs/silius#293]
Currently, bundler accepts only mnemonic phrase and the private key is generated from that. We should add support for loading private key as well.

**Comment by mubarak23** [comment]
@Vid201 can you explain this further, i will like to take this issue

**Comment by Vid201** [comment]
> @Vid201 can you explain this further, i will like to take this issue

Sure, tnx for taking that!

At the moment, bundler only accept CLI argument `mnemonic_file` which is the path to the file containing a mnemonic phrase - from which the private key for bundler is created (https://github.com/silius-rs/silius/blob/main/bin/silius/src/cli/args.rs#L51)

We should add another CLI argument `private_key` which accepts private key (for example the one that you can export from MetaMask) and use that key for bundler

**Comment by iankressin** [comment]
If this is still up for grabs, I can work on it

**Comment by malm0d** [comment]
I actually started working on this a couple of days ago, but I'd be happy to work together on this

**Comment by iankressin** [comment]
> I actually started working on this a couple of days ago, but I'd be happy to work together on this

Awesome. How can I help you?
